// Generated by scripts/build_archive.py. Edit each deck's deck.json instead.
window.SLIDE_ARCHIVE = [
  {
    "title": "Ensemble Mutual",
    "path": "./ensemble-mutual/",
    "date": "2026-10-06",
    "category": "TECH",
    "slideCount": 5,
    "description": "Insurance for AI systems and agents.",
    "thumbnails": [
      "./ensemble-mutual/thumbnails/slide-1.webp",
      "./ensemble-mutual/thumbnails/slide-2.webp",
      "./ensemble-mutual/thumbnails/slide-3.webp"
    ]
  }
];
